name: Deploy Seatly BE to VPS (Docker)

on:
  push:
    branches:
      - main # đổi nếu dùng branch khác

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PORT: 8686 # <-- SSH đang chạy port 8686

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printf "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Deploy to VPS via SSH and Docker Compose
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          SSH_PORT: ${{ env.SSH_PORT }}
        run: |
          ssh -p $SSH_PORT -i ~/.ssh/id_ed25519 $SSH_USER@$SSH_HOST << 'EOF'
            set -e
            cd $PROJECT_PATH

            echo "Pull latest code..."
            git pull origin main

            echo "Build docker image..."
            docker compose build

            echo "Run containers..."
            docker compose up -d

            echo "Done."
          EOF
