name: Seatly BE

on:
  push:
    branches:
      - master # chạy khi push lên branch master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PORT: 8686 # SSH VPS đang chạy port 8686

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printf "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Pull latest code and build docker image
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ env.SSH_PORT }}
        run: |
          ssh -p $SSH_PORT -i ~/.ssh/id_ed25519 $SSH_USER@$SSH_HOST << 'EOF'
            set -e

            PROJECT_PATH="/var/www/seatly-be"
            echo "PROJECT_PATH = $PROJECT_PATH"

            cd "$PROJECT_PATH"

            echo "Current dir:"
            pwd
            echo "List files:"
            ls -a

            echo "Pull latest code..."
            git pull origin master   # hoặc main nếu repo xài main

            echo "Build docker image..."
            docker compose build

            echo "Run containers..."
            docker compose up -d

            echo "Done."
          EOF
